namespace: kong

gateway:
  enabled: true
  
  name: default-kong-gateway
  className: kong
  namespace: {{ template "kong.namespace" . }}
  port: 80
  protocol: HTTP

  proxy:
    type: LoadBalancer
    http:
      servicePort: 80
      containerPort: 8000
    tls:
      servicePort: 443
      containerPort: 8443
      #overrideServiceTargetPort: 8000
    annotations: {}

ingressController:
  enabled: true

  admissionWebhook:
    enabled: true
    certificate:
      provided: false