{{- if .Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1" -}}
apiVersion: gateway.networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1beta1" -}}
apiVersion: gateway.networking.k8s.io/v1beta1
{{- else -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
{{- end }}
kind: Gateway
metadata:
  name: kong-http-gateway
  namespace: kong
  annotations:
    networking.gke.io/certmap: inkcloud-map
spec:
  gatewayClassName: gke-l7-global-external-managed
  addresses:
  - type: NamedAddress
    value: kong-gateway-ip
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    #tls:
    #  mode: Terminate
    #  options:
    #    networking.gke.io/certmap: gcpsandbox-map
    allowedRoutes:
      namespaces:
        from: All
      # namespaces:
      #   from: Selector
      #   selector:
      #     matchLabels:
      #       shared-gateway-access: "true"
  # addresses:
  # - type: NamedAddress
  #   value: my-static-ip

---
{{- if .Values.gateway.enabled -}}
{{- if .Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1" -}}
apiVersion: gateway.networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1beta1" -}}
apiVersion: gateway.networking.k8s.io/v1beta1
{{- else -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
{{- end }}
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
  - name: proxy
    port: {{ .Values.gateway.port }}
    protocol: {{ .Values.gateway.protocol }}
    allowedRoutes:
      namespaces:
        from: All
{{- end }}